enum ErrorCodes {
  BAD_REQUEST = 'RECALLS-BR-01',
  UNAUTHORIZED = 'RECALLS-UA-01',
  FORBIDDEN = 'RECALLS-FB-01',
  TOKEN_EXPIRED = 'RECALLS-FB-02',
  UNRECOGNIZED_API_KEY = 'RECALLS-FB-03',
  MISSING_TOKEN = 'RECALLS-FB-04',
  USAGE_EXCEEDED = 'RECALLS-RL-01',
  TOO_MANY_REQUESTS = 'RECALLS-RL-02',
  URL_NOT_FOUND = 'RECALLS-NF-02',
  NO_DATA_FOUND = 'RECALLS-NF-01',
  CLIENT_SECRET_LIMIT_REACHED = 'RECALLS-PC-01',
  CONFLICT = 'RECALLS-CF-01',
  UNKNOWN = 'RECALLS-UN-01',
}

export default ErrorCodes;
