name: Application CI

on: push

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    uses: dvsa/.github/.github/workflows/nodejs-lint.yaml@v5.0.4
    with:
      node-version: ${{ env.NODE_VERSION }}

  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@v5.0.4
    with:
      test-command: npm run test:ci
      node-version: ${{ env.NODE_VERSION }}

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v5.0.4
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      continue-on-error: false
      args: --all-projects --policy-path=.snyk

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v5.0.4
    needs: [test]
    with:
      upload-artifact: false
      build-folder: dist-build
      build-folder-path: ./hosted/lambda-handlers/dist
      build-command: npm run build:prod
      node-version: ${{ env.NODE_VERSION }}
