name: Application CI

on: push

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    uses: dvsa/.github/.github/workflows/nodejs-lint.yaml@v4.0.1

  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@v4.0.1
    with:
      test-command: npm run test:ci
      npm-version: 9.8.0 # locked at this for now as workspace support removed from lerna in later npm versions

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v4.0.1
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      continue-on-error: false
      args: --all-projects --policy-path=.snyk

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v4.0.1
    needs: [test]
    with:
      upload-artifact: false
      build-folder: dist-build
      build-folder-path: ./hosted/lambda-handlers/dist
      build-command: npm run build:prod
